language: node_js
node_js:
  - "io.js"
env:
  global:
    # GH_TOKEN
    - secure: "TCOqlA20ByGHd7MBuT0Has/O3nGPcsWBEWKZF6/XQZzr+93Chu4wB2n9YGEMotu06UexKFFdKqFWbKMbPDcDOMPGKM5Ofu38/NvIpOJNqukLTIsTeS3rTTaOqL2GgriHMXiopJq9vQwGrNc+VP1VHMmzB8H1FrGKAUoDzzHbBjk="
before_script:
  - git config --global user.email "hello+travis@dominykas.com"
  - git config --global user.name "Travis-CI (dominykas)"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "evh8vXg4Y5L6+opc1/22Aiqrrxfmc9Dpj93eroqAoZX3haDtjZdJDaAxg+vlJLe8OzLODZe8XYkb7SapiRfeA3kJzk3CZD01Wi2wogCB2/ips8QKw8ISInUmAp72rBSvwZzqGy3PSsROsJjMhvfVlGKQgH01mjJJ/q8PL1DNkMk="
    on:
      tags: true
