language: node_js
node_js:
  - "io.js"
env:
  global:
    # GH_TOKEN
    - secure: "PbmvGYY0aJGmMcdq1vhIGIYQKYJCePRs1M0qWG/I3Yd2amvFFHe3Onzqp0D+KS2pnWnBkKrYQsrnPHaaJEg38piT4Q8u8Qi2LO9qc/tgjnvF/WicMqXAAp2JVA+5aEJpHHJT06bTo77Utfd1osRqqZq64hu2SoiSrtvDtp1ZHUQ="
before_script:
  - git config --global user.email "hello+travis@dominykas.com"
  - git config --global user.name "Travis-CI (dominykas)"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "evh8vXg4Y5L6+opc1/22Aiqrrxfmc9Dpj93eroqAoZX3haDtjZdJDaAxg+vlJLe8OzLODZe8XYkb7SapiRfeA3kJzk3CZD01Wi2wogCB2/ips8QKw8ISInUmAp72rBSvwZzqGy3PSsROsJjMhvfVlGKQgH01mjJJ/q8PL1DNkMk="
    on:
      tags: true
