language: node_js
sudo: false
node_js: "iojs-v2.5.0"
env:
  global:
    # GH_TOKEN
    - secure: "TCOqlA20ByGHd7MBuT0Has/O3nGPcsWBEWKZF6/XQZzr+93Chu4wB2n9YGEMotu06UexKFFdKqFWbKMbPDcDOMPGKM5Ofu38/NvIpOJNqukLTIsTeS3rTTaOqL2GgriHMXiopJq9vQwGrNc+VP1VHMmzB8H1FrGKAUoDzzHbBjk="
before_script:
  - git config --global user.email "hello+travis@dominykas.com"
  - git config --global user.name "Travis-CI (dominykas)"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "aRkpCPJ3eYimw0fkbuTq06M1ldP3bxu7Cvq2MzUEk7YCwTIMl8jBi8JV2N6fPC37eCcerlI/sAavi6eL7p89ybKc8s58MvDiKlLLhx3jVxb5taBIX0o2Gn+V/2r5foyVzLGlAPGswU9K6SH6D12GqIKkkJpw8N75ND+z9SRB4Lw="
    on:
      tags: true
